### ISSUE TITLE
error installing pyDNS

### ISSUE THREAD

**Issue by kybrdbnd** [syrusakbary/validate_email#39]
the error says no module named Type
i've version 3.X and also running the cmd via administrator privileges

**Comment by pingometer** [comment]
Try this instead:

`pip install Py3DNS`

**Comment by Slugpotato** [comment]
I also have this problem. I installed Py3DNS and still get this exception: "you must have installed pyDNS python package"

How can I modify the code to accept the new package?

**Comment by mdew192837** [comment]
I have the same problem.

**Comment by saffront** [comment]
Same problem as well.

**Comment by Gabrielvon** [comment]
same problem

**Comment by arpit1997** [comment]
same problem here got this error:

```
Collecting pyDNS
  Downloading pydns-2.3.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0t_9g206/pyDNS/setup.py", line 12, in <module>
        import DNS
      File "/tmp/pip-build-0t_9g206/pyDNS/DNS/__init__.py", line 14, in <module>
        import Type,Opcode,Status,Class
    ImportError: No module named 'Type'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0t_9g206/pyDNS/

```

Anyone found any solution?

**Comment by ghost** [comment]
```
C:\Users\andre>pip install py3DNS
Collecting py3DNS
  Downloading py3dns-3.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\andre\AppData\Local\Temp\pip-build-ajrrsn96\py3DNS\setup.py", line 7, in <module>
        import DNS
      File "C:\Users\andre\AppData\Local\Temp\pip-build-ajrrsn96\py3DNS\DNS\__init__.py", line 37, in <module>
        Base._DiscoverNameServers()
      File "C:\Users\andre\AppData\Local\Temp\pip-build-ajrrsn96\py3DNS\DNS\Base.py", line 84, in _DiscoverNameServers
        return ParseResolvConf()
      File "C:\Users\andre\AppData\Local\Temp\pip-build-ajrrsn96\py3DNS\DNS\Base.py", line 52, in ParseResolvConf
        with open(resolv_path, 'r') as stream:
    FileNotFoundError: [Errno 2] No such file or directory: '/etc/resolv.conf'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\andre\AppData\Local\Temp\pip-build-ajrrsn96\py3DNS\
```

I got the same problem? Any solution? At work I use Python 2 and pyDNS works perfectly. Should I move back to Python 2?

**Comment by mverleg** [comment]
@andre3s That looks like it might be a different problem. `/etc/resolv.conf` is a Linux file and it looks like you're on Windows. I'm not sure what the solution is, but maybe you should open a new `pydns` issue if it doesn't exist yet.

**Comment by mcrowson** [comment]
I'm getting `No module named Opcode`. Same song different verse

**Comment by spetoolio** [comment]
Installing py3DNS works until you actually try and run:

`is_valid = validate_email('example@example.com',verify=True)`

then it returns a NoneType

**Comment by rdhara** [comment]
Having this issue too, would appreciate an update!

**Comment by chameleon10712** [comment]
@pingometer Thanks it works for me!

**Comment by paricapala** [comment]
Anyone have a handle on this error?

**Comment by ghost** [comment]
I have the samme issue. Any updates?

**Comment by davicoradini** [comment]
anything? same issue here!

**Comment by blixten85** [comment]
pip3 install pydns
Collecting pydns
  Using cached pydns-2.3.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-i9okns33/pydns/setup.py", line 12, in <module>
        import DNS
      File "/tmp/pip-build-i9okns33/pydns/DNS/__init__.py", line 14, in <module>
        import Type,Opcode,Status,Class
    ImportError: No module named 'Type'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-i9okns33/pydns/

**Comment by pielco11** [comment]
For `python3` try `pip3 install py3dns`. For `python2` try `pip install pydns`.
These work for me.

If you do `pip3 install pydns` you are trying to install a python2 version of a package for python3, and _vice versa_.

**Comment by pielco11** [comment]
#76

**Comment by eazrael** [comment]
Thanks pielco11. This solved this for me :-)

**Comment by nitindhamu** [comment]
I was getting an error while using "import dns.resolver". I tried dnspython, py3dns but they failed.
dns won't install. after much hit and try I installed pubdns module and it solved my problem.

**Comment by nitindhamu** [comment]
I was getting an error while using "import dns.resolver". I tried dnspython, py3dns but they failed.
dns won't install. after much hit and try I installed pubdns module and it solved my problem.

**Comment by L3arn3D** [comment]
I was getting an error while using "import dns.resolver". I tried dnspython, py3dns but they failed.
dns won't install. after much hit and try I installed pubdns module and it solved my problem.

**Comment by ThatOneCalculator** [comment]
> For `python3` try `pip3 install py3dns`. For `python2` try `pip install pydns`.
> These work for me.
> 
> If you do `pip3 install pydns` you are trying to install a python2 version of a package for python3, and _vice versa_.

Worked perfectly. Thank you!

**Comment by rohitbaby** [comment]
> Try this instead:
> 
> `pip install Py3DNS`

I have py3dns installed but my code gives me following error

"For checking the mx records or checking if the email exists you must have installed pyDNS python package"

**Comment by rohitbaby** [comment]
> I also have this problem. I installed Py3DNS and still get this exception: "you must have installed pyDNS python package"
> 
> How can I modify the code to accept the new package?


Referencing the following thread
https://github.com/syrusakbary/validate_email/issues/72

I installed it via Anaconda Prompt using pip install py3DNS. Conda and cmd install did not work for me.

**Comment by gauthierbuttez** [comment]
I am using python 3.7.7
I tried everything proposed above, and nothing works. Any help please?

**Comment by AnkitVats21** [comment]
Thank You
@pielco11

**Comment by shaikhmaaz04** [comment]
> I was getting an error while using "import dns.resolver". I tried dnspython, py3dns but they failed. dns won't install. after much hit and try I installed pubdns module and it solved my problem.



> > For `python3` try `pip3 install py3dns`. For `python2` try `pip install pydns`.
> > These work for me.
> > If you do `pip3 install pydns` you are trying to install a python2 version of a package for python3, and _vice versa_.
> 
> Worked perfectly. Thank you!

validate-email-address still requires pydns only is there any way to use py3dns

**Comment by ThatOneCalculator** [comment]
The last release on this repo was 9 years ago, you're probably better off using a newer library like [this](https://pypi.org/project/validate-dns-email/) or [this](https://pypi.org/project/email-validate/) or [this](https://gitea.ksol.io/karolyi/py3-validate-email)
