### ISSUE TITLE
Returns none when using provider that blocks port 25

### ISSUE THREAD

**Issue by jmdahling** [syrusakbary/validate_email#61]
This happens to any customers using xfinity for example - see:
https://www.xfinity.com/support/internet/email-port-25-no-longer-supported/

Recommend that the script be updated to utilize port 587 to avoid additional bugs due to return of "None"

**Comment by jmdahling** [comment]
Here's how I tested and discovered this:
>>> import smtplib
>>> smtp = smtplib.SMTP(timeout=5)
>>> smtp.connect('smtp.gmail.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.timeout: timed out
>>> smtp = smtplib.SMTP(port=587, timeout=5)
>>> smtp.connect('smtp.gmail.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.timeout: timed out
>>> smtp.connect('smtp.gmail.com', port=587)
(220, 'smtp.gmail.com ESMTP o189sm28894377pga.12 - gsmtp')
>>>

**Comment by jayvdb** [comment]
[`smtplib.SMTP_SSL`](https://docs.python.org/3/library/smtplib.html#smtplib.SMTP_SSL) should be used first, and then `smtplib.SMTP`.

**Comment by i2dcarrasco** [comment]
Hello,

Is there any plan to fix this issue?. I've the same issue because some cloud providers block port 25 (like FCP for example), and then the script is unable to connect.

Thanks!

**Comment by liamdn8** [comment]
I got the same Issue when using AWS lambda. So I contacted support and then they removed port 25 throttle.
I think that was only way

**Comment by njkevlani** [comment]
Google Cloud also blocks outgoing traffic on port 25. Details [here](https://cloud.google.com/vpc/docs/firewalls#blockedtraffic).
