### ISSUE TITLE
support for python3 and/or py3dns

### ISSUE THREAD

**Issue by Sil68** [syrusakbary/validate_email#72]
will there be support for python3 and/or py3dns

**Comment by pielco11** [comment]
I use this package as 3rd party tool for a python3 project, so if you want to use this in python3 just install py3dns and run with python3. This works for me, also you don't need to change the code.

**Comment by Sil68** [comment]
Using _validate_email_ just for validating the format of an email address, work like a charm even with Python3, only when trying to verify the corresponding smtp server, or even the reachability of the email address, I'm receiving an error message, reading that package 'pyDNS' is required, despite the fact the I've installed & imported 'py3DNS'.

**Comment by pielco11** [comment]
You just have to install `py3DNS` and **not** import py3dns, just leave everything as it is (and so import pydns, as wrote in the code). At least this works for me.

**Comment by Sil68** [comment]
I'm afraid, here at my end this is causing an exception raised:

```
>>> validate_email('a.b@c.d', verify=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/pyenv/versions/3.6.4/lib/python3.6/site-packages/validate_email.py", line 131, in validate_email
    raise Exception('For check the mx records or check if the email exists you must '
Exception: For check the mx records or check if the email exists you must have installed pyDNS python package
```

**Comment by pielco11** [comment]
I'm sorry, my bad. Try with `sudo -H pip3 install py3dns` and after that open `python3` and `import DNS`.

**Comment by Sil68** [comment]
No worries there mate, like this it worked like a charm! Thanks!

**Comment by tengerdata** [comment]
I installed py3dns on my conda env, where I use python 3, but I still get this error: `Exception: For check the mx records or check if the email exists you must have installed pyDNS python package`

When I try to import DNS,  as you suggested in your comment, I get `ImportError: No module named 'DNS'`

I tried to make this work for about an hour, but I can't wrap my head around this problem.

Please let me know your thoughts.

**Comment by Sil68** [comment]
I just bumped into this yesterday when I was trying to move from python 3.6.4 to 3.6.5, and also when trying to get 3.7.0b3 up & running.

Looking into the site package directory of 3.6.5 or 3.7.0b3 there’s one called ‘dns’ (at least on my Mac), but when checking with the working 3.6.4 installation, it’s spelled ‘DNS’ there.

**Comment by tengerdata** [comment]
@Sil68 Thanks for your reply. I tried everything to make this work but it seems it's impossible for me to get this sorted out.

Whatever I do, I get the same error: `Exception: For check the mx records or check if the email exists you must have installed pyDNS python package`

It's too long to list here everything I tried.

This is starting to be frustrating and really annoying.

**Comment by hbg** [comment]
Any solution?

**Comment by sertraline** [comment]
dnspython imports as `dns` and py3dns imports as `DNS`. Seems like there's name conflict. `import DNS` worked for me when I uninstalled dnspython package.
`pip uninstall py3dns dnspython`
`pip install py3dns`

**Comment by fguille94** [comment]
> dnspython imports as `dns` and py3dns imports as `DNS`. Seems like there's name conflict. `import DNS` worked for me when I uninstalled dnspython package.
> `pip uninstall py3dns dnspython`
> `pip install py3dns`

I tried this and the error changed from the original "you must have installed pydns" to "DNS.Base.TimeoutError" and I have no idea why, my suspicion is on removing the dnspython package but what do I know

**Comment by chinmaymisra** [comment]
I am also facing a similar issue, pyDNS is not getting installed at all, while I have managed to install py3DNS, still I am getting the message that pyDNS must be installed when I try to verify SMTP for an email id. I use Anaconda on Windows. Any help would be appreciated.

**Comment by altdatum** [comment]
Trying to isntall py3DNS through Anaconda conda install -c auto py3dns and getting an error: PackagesNotFoundError: The following packages are not available from current channels:

**Comment by lluflliks** [comment]
I installed it without problems in Anaconda using pip install py3DNS.  Conda install didn't work for me :(

**Comment by altdatum** [comment]
Don’t use Anaconda to install python, download python directly to your computer without Anaconda. Then install py3DNS

https://www.altdatum.com/validate-emails-with-python/




[Trans Thumb]

Ryan Gilford
alt Datum<https://www.altdatum.com/>
(949) 216-4576<tel:(949)%20216-4576> opt 2
rgilford@altdatum.com<mailto:rgilford@altdatum.com>

On Mar 4, 2020, at 11:59 PM, XXxxCarbon6xxXX <notifications@github.com> wrote:

﻿

I installed it without problems in Anaconda using pip install py3DNS. Conda install didn't work for me :(

**Comment by InferGuard** [comment]
### Step 1 remove dnspython : 
`pip uninstall dnspython
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Found existing installation: dnspython 1.15.0
Uninstalling dnspython-1.15.0:
  Would remove:
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/*
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dnspython-1.15.0.dist-info/*
  Would not remove (might be manually added):
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/Base.py
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/Base.pyo
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/Class.py
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/Class.pyo
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/Lib.py
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/Lib.pyo
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/Opcode.py
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/Opcode.pyo
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/Status.py
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/Status.pyo
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/Type.py
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/Type.pyo
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/lazy.py
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/lazy.pyo
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/win32dns.py
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dns/win32dns.pyo
Proceed (y/n)? y
  Successfully uninstalled dnspython-1.15.0`

### Step 2 remove pyDNS :
`pip uninstall pydns
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Found existing installation: pydns 2.3.6
Uninstalling pydns-2.3.6:
  Would remove:
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/DNS/Base.py
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/DNS/Base.pyo
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/DNS/Class.py
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/DNS/Class.pyo
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/DNS/Lib.py
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/DNS/Lib.pyo
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/DNS/Status.py
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/DNS/Status.pyo
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/DNS/Type.py
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/DNS/Type.pyo
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/DNS/lazy.py
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/DNS/lazy.pyo
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/DNS/win32dns.py
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/DNS/win32dns.pyo
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pydns-2.3.6.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled pydns-2.3.6`

### Step 2 Install pyDNS again  :
`pip install pydns
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /Library/Caches/pip/wheels/54/c3/70/622b2f4958520225fab47eceb1e2659ac4d03ec6760ec26024/pydns-2.3.6-py2-none-any.whl
Installing collected packages: pydns
Successfully installed pydns-2.3.6`

### Step 3 Check the installed package with : 
`python -m DNS
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named DNS.__main__; 'DNS' is a package and cannot be directly executed`

**Comment by juslintek** [comment]
I get this error:
```
root@hosting:~# sudo -H pip3 install py3dns
Collecting py3dns
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/8a/b7/bd0fca1b330527ccf5f47a586900797dd1e054909f7d4c5e287de8b3fe59/py3dns-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-63eia9rl/py3dns/setup.py", line 7, in <module>
        import DNS
      File "/tmp/pip-build-63eia9rl/py3dns/DNS/__init__.py", line 37, in <module>
        Base._DiscoverNameServers()
      File "/tmp/pip-build-63eia9rl/py3dns/DNS/Base.py", line 85, in _DiscoverNameServers
        return ParseResolvConf()
      File "/tmp/pip-build-63eia9rl/py3dns/DNS/Base.py", line 54, in ParseResolvConf
        return ParseResolvConfFromIterable(stream)
      File "/tmp/pip-build-63eia9rl/py3dns/DNS/Base.py", line 59, in ParseResolvConfFromIterable
        for line in lines:
      File "/usr/lib/python3.6/codecs.py", line 321, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 34: invalid continuation byte

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-63eia9rl/py3dns/
```

**Comment by renato-gallo** [comment]
> dnspython imports as `dns` and py3dns imports as `DNS`. Seems like there's name conflict. `import DNS` worked for me when I uninstalled dnspython package. `pip uninstall py3dns dnspython` `pip install py3dns`

This worked like a charm... never had another problem with the validate_email_address library. Cheers!
