### ISSUE TITLE
The issue during the installation of pyDNS

### ISSUE THREAD

**Issue by e-grn** [syrusakbary/validate_email#76]
Hello.
There is no problem with validate-email. But I have some issue during the installation of pyDNS:

```
C:\anaconda\Scripts>pip install pyDNS
Collecting pyDNS
  Using cached pydns-2.3.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Eugene\AppData\Local\Temp\pip-build-6ybbzf69\pyDNS\setup.py", line 12, in <module>
        import DNS
      File "C:\Users\Eugene\AppData\Local\Temp\pip-build-6ybbzf69\pyDNS\DNS\__init__.py", line 14, in <module>
        import Type,Opcode,Status,Class
    ModuleNotFoundError: No module named 'Type'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Eugene\AppData\Local\Temp\pip-build-6ybbzf69\pyDNS\
```

I have Win10x64. Conda 4.3.34.

**Comment by k-ogawa-1988** [comment]
Same issue occurs on macOS 10.13.
```
> pip install pyDNS
Collecting pyDNS
  Downloading pydns-2.3.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cv/8g1rs8bj7g51v305nbqhp7640000gp/T/pip-build-8w94ulf9/pyDNS/setup.py", line 12, in <module>
        import DNS
      File "/private/var/folders/cv/8g1rs8bj7g51v305nbqhp7640000gp/T/pip-build-8w94ulf9/pyDNS/DNS/__init__.py", line 14, in <module>
        import Type,Opcode,Status,Class
    ModuleNotFoundError: No module named 'Type'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/cv/8g1rs8bj7g51v305nbqhp7640000gp/T/pip-build-8w94ulf9/pyDNS/
```

**Comment by k-ogawa-1988** [comment]
Ah, I'm sorry.
I found this https://github.com/syrusakbary/validate_email/issues/72
Using py3dns fixes this problem in my environment because I will use this on Python3.6

**Comment by pielco11** [comment]
![immagine](https://user-images.githubusercontent.com/17363750/38210216-0aa1f6ee-36b7-11e8-872d-b1c1bb04c23f.png)

And the same should be (actually is, but I'll wait the confirm) for @k-eugene 

It's not a problem with the package but with the python version that you are using.

**Comment by e-grn** [comment]
Hello. I tried to install py3dns:

```
C:\anaconda\Scripts>pip install py3DNS
Collecting py3DNS
  Downloading py3dns-3.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Eugene\AppData\Local\Temp\pip-build-xlagdvq1\py3DNS\setup.py", line 7, in <module>
        import DNS
      File "C:\Users\Eugene\AppData\Local\Temp\pip-build-xlagdvq1\py3DNS\DNS\__init__.py", line 37, in <module>
        Base._DiscoverNameServers()
      File "C:\Users\Eugene\AppData\Local\Temp\pip-build-xlagdvq1\py3DNS\DNS\Base.py", line 84, in _DiscoverNameServers
        return ParseResolvConf()
      File "C:\Users\Eugene\AppData\Local\Temp\pip-build-xlagdvq1\py3DNS\DNS\Base.py", line 52, in ParseResolvConf
        with open(resolv_path, 'r') as stream:
    FileNotFoundError: [Errno 2] No such file or directory: '/etc/resolv.conf'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Eugene\AppData\Local\Temp\pip-build-xlagdvq1\py3DNS\
```

**Comment by grijalva10** [comment]
this worked for me. `pip install py3dns==3.1.1a0`

**Comment by Greedy-Vulture** [comment]
@grijalva10 this worked for me as well

**Comment by racitup** [comment]
@grijalva10 this worked for me too.
However, now I get this: #79

**Comment by boldrack** [comment]
@grijalva10 worked for me too

**Comment by hanleilei** [comment]
@grijalva10 thanks, I fixed it in these way:

`
pip install py3dns==3.1.1
Collecting py3dns==3.1.1
  Could not find a version that satisfies the requirement py3dns==3.1.1 (from versions: 3.0.4, 3.1.0, 3.1.1a0, 3.2.0)
No matching distribution found for py3dns==3.1.1
`

and install the latest

**Comment by hanleilei** [comment]
I found this module highly depends on the pydns, for example, if I want to verify the 'ding.guibian@gmail', this function return true..what should i say??

try this regexp instead:
`/^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/`

**Comment by SaMPada-KulkaRn1** [comment]
python3.6 -m pip install py3dns==3.1.1a0
Solves the issues for me. Apparently it is giving issues for Python 3.7

**Comment by rohitbaby** [comment]
For Python 3.7 anyone got the resolution for py3dns / pyDNS?

I get the following for pip install pyDNS

    ERROR: Command errored out with exit status 1:
     command: 'c:\users\ajroya\appdata\local\programs\python\python37-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\AJROYA\\AppData\\Local\\Temp\\pip-install-uff8u_a_\\pyDNS\\setup.py'"'"'; __file__='"'"'C:\\Users\\AJROYA\\AppData\\Local\\Temp\\pip-install-uff8u_a_\\pyDNS\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\AJROYA\AppData\Local\Temp\pip-install-uff8u_a_\pyDNS\pip-egg-info'
         cwd: C:\Users\AJROYA\AppData\Local\Temp\pip-install-uff8u_a_\pyDNS\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\AJROYA\AppData\Local\Temp\pip-install-uff8u_a_\pyDNS\setup.py", line 12, in <module>
        import DNS
      File "C:\Users\AJROYA\AppData\Local\Temp\pip-install-uff8u_a_\pyDNS\DNS\__init__.py", line 14, in <module>
        import Type,Opcode,Status,Class
    ModuleNotFoundError: No module named 'Type'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by OmarKHerj** [comment]
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"                                                                                 '"'/tmp/pip-install-9vo8eu8a/pydns/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9vo8                                                                                 eu8a/pydns/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.r                                                                                 ead().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"                                                                                 '"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-58qrqlvg                                                                                                    
         cwd: /tmp/pip-install-9vo8eu8a/pydns/                                                                                                                        
    Complete output (7 lines):                                                                                                                                        
    Traceback (most recent call last):                                                                                                                                
      File "<string>", line 1, in <module>                                                                                                                            
      File "/tmp/pip-install-9vo8eu8a/pydns/setup.py", line 12, in <module>                                                                                           
        import DNS                                                                                                                                                    
      File "/tmp/pip-install-9vo8eu8a/pydns/DNS/__init__.py", line 14, in <module>                                                                                    
        import Type,Opcode,Status,Class                                                                                                                               
    ModuleNotFoundError: No module named 'Type'                                                                                                                       
    ----------------------------------------                                                                                                                          
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.       



i have the same problem i need pydns to run knockmail , and i already have py3dns any solution ???
