### ISSUE TITLE
Using socks for proxy 

### ISSUE THREAD

**Issue by 2803media** [syrusakbary/validate_email#77]
As I understand for large volume there is a risk of being ban so why not using a proxy.
```

import socks
import socket

proxy_host = 'domain.com'
proxy_port = 1080
proxy_username = 'user'
proxy_password = 'pass'

socks.setdefaultproxy(socks.PROXY_TYPE_SOCKS5,proxy_host,proxy_port,True,proxy_username,proxy_password)
socket.socket = socks.socksocket

```

Do you know how to combine this with validate_email?

I have this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/DNS/Base.py", line 323, in req
    self.sendUDPRequest(server)
  File "/usr/local/lib/python3.4/dist-packages/DNS/Base.py", line 376, in sendUDPRequest
    raise first_socket_error
  File "/usr/local/lib/python3.4/dist-packages/DNS/Base.py", line 351, in sendUDPRequest
    r=self.processUDPReply()
  File "/usr/local/lib/python3.4/dist-packages/DNS/Base.py", line 135, in processUDPReply
    (self.reply, self.from_address) = self.s.recvfrom(65535)
  File "/usr/local/lib/python3.4/dist-packages/socks.py", line 448, in recvfrom
    buf = BytesIO(super(socksocket, self).recv(bufsize + 1024, flags))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/data/public_html/test/check.py", line 54, in <module>
    is_valid = validate_email('t@domaine.fr',verify=True)#
  File "/usr/local/lib/python3.4/dist-packages/validate_email.py", line 134, in validate_email
    mx_hosts = get_mx_ip(hostname)
  File "/usr/local/lib/python3.4/dist-packages/validate_email.py", line 102, in get_mx_ip
    MX_DNS_CACHE[hostname] = DNS.mxlookup(hostname)
  File "/usr/local/lib/python3.4/dist-packages/DNS/lazy.py", line 54, in mxlookup
    l = dnslookup(name, qtype = 'mx')
  File "/usr/local/lib/python3.4/dist-packages/DNS/lazy.py", line 37, in dnslookup
    result = Base.DnsRequest(name=name, qtype=qtype).req()
  File "/usr/local/lib/python3.4/dist-packages/DNS/Base.py", line 327, in req
    raise SocketError(reason)
DNS.Base.SocketError: [Errno 111] Connection refused
```

**Comment by taewookim** [comment]
would love hear if anyone's been able to solve this
