### ISSUE TITLE
DNS.Base.SocketError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

### ISSUE THREAD

**Issue by racitup** [syrusakbary/validate_email#79]
Hi,

I'm getting the following error when trying either check_mx or verify on Windows 10.

Symptoms updated: This occurs about 3000 addresses into a job of maybe 7000 email addresses.
It is unrelated to having run the same job before with or without a reboot.

Admittedly it seems to be an Alpha version of py3dns (py3dns==3.1.1a0) to work around another error I was getting on python 3.6.5.

Full error:

> Traceback (most recent call last):
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\DNS\Base.py", line 323, in req
>     self.sendUDPRequest(server)
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\DNS\Base.py", line 376, in sendUDPRequest
>     raise first_socket_error
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\DNS\Base.py", line 348, in sendUDPRequest
>     self.conn()
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\DNS\Base.py", line 219, in conn
>     self.getSource()
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\DNS\Base.py", line 212, in getSource
>     self.s.bind(('', source_port))
> OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "bad_nav_custom_report_selection_emails.py", line 48, in <module>
>     r = validate_nav_csv(f)
>   File "bad_nav_custom_report_selection_emails.py", line 38, in validate_nav_csv
>     if not validate_email(e, check_mx=True):
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\validate_email.py", line 134, in validate_email
>     mx_hosts = get_mx_ip(hostname)
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\validate_email.py", line 102, in get_mx_ip
>     MX_DNS_CACHE[hostname] = DNS.mxlookup(hostname)
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\DNS\lazy.py", line 54, in mxlookup
>     l = dnslookup(name, qtype = 'mx')
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\DNS\lazy.py", line 37, in dnslookup
>     result = Base.DnsRequest(name=name, qtype=qtype).req()
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\DNS\Base.py", line 327, in req
>     raise SocketError(reason)
> DNS.Base.SocketError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

```
>pip freeze
py3dns==3.1.1
validate-email==1.3
```

**Comment by racitup** [comment]
Reported upstream [here](https://bugs.launchpad.net/py3dns/+bug/1767069)
